import { PipelineData } from "@automl/domain";

/**
 * Mẫu 1: Dữ liệu mẫu rỗng ban đầu từ mock_api (profiles/regresion_v1.json)
 * Mọi giá trị runtime (status, timestamps, output) đều là null.
 */
export const MOCK_PIPELINE_EMPTY: PipelineData = {
  job_id: "job-001",
  version: "1.0.0",
  mode: "automl",
  status: null,
  updated_at: null,
  read_dataset: {
    name: "Read dataset",
    kind: "data_loading",
    depends_on: [],
    status: null,
    started_at: null,
    finished_at: null,
    error: null,
    params: {
      id_data: null,
      format: "parquet",
    },
    output: {
      data_url: null,
      cache_hit: null,
    },
  },
  split_holdout_data: {
    name: "Split holdout data",
    kind: "data_splitting",
    depends_on: ["read_dataset"],
    status: null,
    started_at: null,
    finished_at: null,
    error: null,
    params: {
      method: "train_test_split",
      test_size: 0.2,
      shuffle: true,
      random_state: 42,
    },
    output: {
      train_rows: null,
      holdout_rows: null,
    },
  },
  read_training_data: {
    name: "Read training data",
    kind: "data_loading",
    depends_on: ["split_holdout_data"],
    status: null,
    started_at: null,
    finished_at: null,
    error: null,
    params: {
      split: "train",
    },
    output: {
      n_rows: null,
      n_columns: null,
    },
  },
  preprocessing: {
    name: "Preprocessing",
    kind: "preprocessing",
    depends_on: ["read_training_data"],
    status: null,
    started_at: null,
    finished_at: null,
    error: null,
    params: {
      list_feature: ["crim", "zn", "indus", "chas", "nox", "rm", "age", "dis", "rad", "tax", "ptratio", "b", "lstat"],
      target: "medv",
      transformers: {
        numeric: ["SimpleImputer", "StandardScaler"],
        categorical: ["SimpleImputer", "OneHotEncoder"],
        text: ["SimpleImputer", "TfidfVectorizer"],
      },
    },
    output: {
      cache_hit: null,
      dropped_rows: null,
      column_types: {
        numeric: [],
        categorical: [],
        text: [],
      },
    },
  },
  model_selection: {
    name: "Model selection",
    kind: "model_selection",
    depends_on: ["preprocessing"],
    status: null,
    started_at: null,
    finished_at: null,
    error: null,
    params: {
      problem_type: "regression",
      model_names: [
        "LinearRegression",
        "DecisionTreeRegressor",
        "RandomForestRegressor",
        "GradientBoostingRegressor",
        "XGBRegressor",
      ],
      search_algorithm: null,
      max_time: null,
      metric_sort: "r2",
      metrics: {
        mse: "minimize",
        mae: "minimize",
        mape: "minimize",
        r2: "maximize",
      },
      split: {
        method: "KFold",
        n_splits: 5,
        shuffle: true,
        random_state: 42,
      },
    },
    output: {},
  },
  train: {
    name: "Train models",
    kind: "model_training",
    depends_on: ["model_selection"],
    status: null,
    started_at: null,
    finished_at: null,
    error: null,
    params: {},
    output: {
      models: {
        LinearRegression: {
          status: null,
          error: null,
          best_params: null,
          scores: null,
        },
        DecisionTreeRegressor: {
          status: null,
          error: null,
          best_params: null,
          scores: null,
        },
        RandomForestRegressor: {
          status: null,
          error: null,
          best_params: null,
          scores: null,
        },
        GradientBoostingRegressor: {
          status: null,
          error: null,
          best_params: null,
          scores: null,
        },
        XGBRegressor: {
          status: null,
          error: null,
          best_params: null,
          scores: null,
        },
      },
    },
  },
  select_best: {
    name: "Select best model",
    kind: "model_selection",
    depends_on: ["train"],
    status: null,
    started_at: null,
    finished_at: null,
    error: null,
    params: {
      dependency_policy: "all_terminal",
    },
    output: {
      best_model: null,
      time_limit_reached: null,
    },
  },
  save_result: {
    name: "Save result",
    kind: "result_storage",
    depends_on: ["select_best"],
    status: null,
    started_at: null,
    finished_at: null,
    error: null,
    params: {
      bucket_name: "models",
    },
    output: {
      object_name: null,
    },
  },
};

/**
 * Mẫu 2: Đang thực thi huấn luyện (Running state)
 */
export const MOCK_PIPELINE_RUNNING: PipelineData = {
  job_id: "job-001",
  version: "1.0.0",
  mode: "automl",
  status: "running",
  updated_at: "2026-10-06T09:30:00Z",
  read_dataset: {
    name: "Read dataset",
    kind: "data_loading",
    depends_on: [],
    status: "done",
    started_at: "2026-10-06T09:28:10Z",
    finished_at: "2026-10-06T09:28:22Z",
    error: null,
    params: {
      id_data: "ds_housing_2026",
      format: "parquet",
    },
    output: {
      data_url: "minio://datasets/housing_train.parquet",
      cache_hit: false,
    },
  },
  split_holdout_data: {
    name: "Split holdout data",
    kind: "data_splitting",
    depends_on: ["read_dataset"],
    status: "done",
    started_at: "2026-10-06T09:28:23Z",
    finished_at: "2026-10-06T09:28:30Z",
    error: null,
    params: {
      method: "train_test_split",
      test_size: 0.2,
      shuffle: true,
      random_state: 42,
    },
    output: {
      train_rows: 8000,
      holdout_rows: 2000,
    },
  },
  read_training_data: {
    name: "Read training data",
    kind: "data_loading",
    depends_on: ["split_holdout_data"],
    status: "done",
    started_at: "2026-10-06T09:28:31Z",
    finished_at: "2026-10-06T09:28:38Z",
    error: null,
    params: {
      split: "train",
    },
    output: {
      n_rows: 8000,
      n_columns: 14,
    },
  },
  preprocessing: {
    name: "Preprocessing",
    kind: "preprocessing",
    depends_on: ["read_training_data"],
    status: "done",
    started_at: "2026-10-06T09:28:39Z",
    finished_at: "2026-10-06T09:29:10Z",
    error: null,
    params: {
      list_feature: ["crim", "zn", "indus", "chas", "nox", "rm", "age", "dis", "rad", "tax", "ptratio", "b", "lstat"],
      target: "medv",
      transformers: {
        numeric: ["SimpleImputer", "StandardScaler"],
        categorical: ["SimpleImputer", "OneHotEncoder"],
        text: ["SimpleImputer", "TfidfVectorizer"],
      },
    },
    output: {
      cache_hit: true,
      dropped_rows: 0,
      column_types: {
        numeric: ["crim", "zn", "indus", "nox", "rm", "age", "dis", "rad", "tax", "ptratio", "b", "lstat"],
        categorical: ["chas"],
        text: [],
      },
    },
  },
  model_selection: {
    name: "Model selection",
    kind: "model_selection",
    depends_on: ["preprocessing"],
    status: "done",
    started_at: "2026-10-06T09:29:11Z",
    finished_at: "2026-10-06T09:29:15Z",
    error: null,
    params: {
      problem_type: "regression",
      model_names: [
        "LinearRegression",
        "DecisionTreeRegressor",
        "RandomForestRegressor",
        "GradientBoostingRegressor",
        "XGBRegressor",
      ],
      search_algorithm: "BayesianSearch",
      max_time: 3600,
      metric_sort: "r2",
      metrics: {
        mse: "minimize",
        mae: "minimize",
        mape: "minimize",
        r2: "maximize",
      },
      split: {
        method: "KFold",
        n_splits: 5,
        shuffle: true,
        random_state: 42,
      },
    },
    output: {},
  },
  train: {
    name: "Train models",
    kind: "model_training",
    depends_on: ["model_selection"],
    status: "running",
    started_at: "2026-10-06T09:29:16Z",
    finished_at: null,
    error: null,
    params: {},
    output: {
      models: {
        LinearRegression: {
          status: "done",
          error: null,
          best_params: { fit_intercept: true, positive: false },
          scores: { r2: 0.7245, mse: 34.12, mae: 4.62, mape: 0.155 },
        },
        DecisionTreeRegressor: {
          status: "done",
          error: null,
          best_params: { max_depth: 8, min_samples_split: 5 },
          scores: { r2: 0.7621, mse: 28.45, mae: 4.05, mape: 0.138 },
        },
        RandomForestRegressor: {
          status: "running",
          error: null,
          best_params: null,
          scores: null,
        },
        GradientBoostingRegressor: {
          status: "pending",
          error: null,
          best_params: null,
          scores: null,
        },
        XGBRegressor: {
          status: "pending",
          error: null,
          best_params: null,
          scores: null,
        },
      },
    },
  },
  select_best: {
    name: "Select best model",
    kind: "model_selection",
    depends_on: ["train"],
    status: "pending",
    started_at: null,
    finished_at: null,
    error: null,
    params: {
      dependency_policy: "all_terminal",
    },
    output: {
      best_model: null,
      time_limit_reached: null,
    },
  },
  save_result: {
    name: "Save result",
    kind: "result_storage",
    depends_on: ["select_best"],
    status: "pending",
    started_at: null,
    finished_at: null,
    error: null,
    params: {
      bucket_name: "models",
    },
    output: {
      object_name: null,
    },
  },
};

/**
 * Mẫu 3: Đã hoàn tất thành công toàn bộ (Completed State)
 */
export const MOCK_PIPELINE_COMPLETED: PipelineData = {
  job_id: "job-001",
  version: "1.0.0",
  mode: "automl",
  status: "done",
  updated_at: "2026-10-06T09:35:45Z",
  read_dataset: {
    name: "Read dataset",
    kind: "data_loading",
    depends_on: [],
    status: "done",
    started_at: "2026-10-06T09:28:10Z",
    finished_at: "2026-10-06T09:28:22Z",
    error: null,
    params: {
      id_data: "ds_housing_2026",
      format: "parquet",
    },
    output: {
      data_url: "minio://datasets/housing_train.parquet",
      cache_hit: true,
    },
  },
  split_holdout_data: {
    name: "Split holdout data",
    kind: "data_splitting",
    depends_on: ["read_dataset"],
    status: "done",
    started_at: "2026-10-06T09:28:23Z",
    finished_at: "2026-10-06T09:28:30Z",
    error: null,
    params: {
      method: "train_test_split",
      test_size: 0.2,
      shuffle: true,
      random_state: 42,
    },
    output: {
      train_rows: 8000,
      holdout_rows: 2000,
    },
  },
  read_training_data: {
    name: "Read training data",
    kind: "data_loading",
    depends_on: ["split_holdout_data"],
    status: "done",
    started_at: "2026-10-06T09:28:31Z",
    finished_at: "2026-10-06T09:28:38Z",
    error: null,
    params: {
      split: "train",
    },
    output: {
      n_rows: 8000,
      n_columns: 14,
    },
  },
  preprocessing: {
    name: "Preprocessing",
    kind: "preprocessing",
    depends_on: ["read_training_data"],
    status: "done",
    started_at: "2026-10-06T09:28:39Z",
    finished_at: "2026-10-06T09:29:10Z",
    error: null,
    params: {
      list_feature: ["crim", "zn", "indus", "chas", "nox", "rm", "age", "dis", "rad", "tax", "ptratio", "b", "lstat"],
      target: "medv",
      transformers: {
        numeric: ["SimpleImputer", "StandardScaler"],
        categorical: ["SimpleImputer", "OneHotEncoder"],
        text: ["SimpleImputer", "TfidfVectorizer"],
      },
    },
    output: {
      cache_hit: true,
      dropped_rows: 0,
      column_types: {
        numeric: ["crim", "zn", "indus", "nox", "rm", "age", "dis", "rad", "tax", "ptratio", "b", "lstat"],
        categorical: ["chas"],
        text: [],
      },
    },
  },
  model_selection: {
    name: "Model selection",
    kind: "model_selection",
    depends_on: ["preprocessing"],
    status: "done",
    started_at: "2026-10-06T09:29:11Z",
    finished_at: "2026-10-06T09:29:15Z",
    error: null,
    params: {
      problem_type: "regression",
      model_names: [
        "LinearRegression",
        "DecisionTreeRegressor",
        "RandomForestRegressor",
        "GradientBoostingRegressor",
        "XGBRegressor",
      ],
      search_algorithm: "Hyperband",
      max_time: 3600,
      metric_sort: "r2",
      metrics: {
        mse: "minimize",
        mae: "minimize",
        mape: "minimize",
        r2: "maximize",
      },
      split: {
        method: "KFold",
        n_splits: 5,
        shuffle: true,
        random_state: 42,
      },
    },
    output: {},
  },
  train: {
    name: "Train models",
    kind: "model_training",
    depends_on: ["model_selection"],
    status: "done",
    started_at: "2026-10-06T09:29:16Z",
    finished_at: "2026-10-06T09:34:50Z",
    error: null,
    params: {},
    output: {
      models: {
        LinearRegression: {
          status: "done",
          error: null,
          best_params: { fit_intercept: true, copy_X: true },
          scores: { r2: 0.7245, mse: 34.12, mae: 4.62, mape: 0.155 },
        },
        DecisionTreeRegressor: {
          status: "done",
          error: null,
          best_params: { max_depth: 8, min_samples_split: 5, criterion: "squared_error" },
          scores: { r2: 0.7621, mse: 28.45, mae: 4.05, mape: 0.138 },
        },
        RandomForestRegressor: {
          status: "done",
          error: null,
          best_params: { n_estimators: 200, max_depth: 12, min_samples_leaf: 2 },
          scores: { r2: 0.8841, mse: 15.62, mae: 2.81, mape: 0.094 },
        },
        GradientBoostingRegressor: {
          status: "done",
          error: null,
          best_params: { n_estimators: 250, learning_rate: 0.08, max_depth: 6 },
          scores: { r2: 0.8654, mse: 18.23, mae: 3.12, mape: 0.103 },
        },
        XGBRegressor: {
          status: "done",
          error: null,
          best_params: { n_estimators: 400, learning_rate: 0.04, max_depth: 7, subsample: 0.85 },
          scores: { r2: 0.9124, mse: 12.35, mae: 2.45, mape: 0.082 },
        },
      },
    },
  },
  select_best: {
    name: "Select best model",
    kind: "model_selection",
    depends_on: ["train"],
    status: "done",
    started_at: "2026-10-06T09:34:51Z",
    finished_at: "2026-10-06T09:35:00Z",
    error: null,
    params: {
      dependency_policy: "all_terminal",
    },
    output: {
      best_model: "XGBRegressor",
      time_limit_reached: false,
    },
  },
  save_result: {
    name: "Save result",
    kind: "result_storage",
    depends_on: ["select_best"],
    status: "done",
    started_at: "2026-10-06T09:35:01Z",
    finished_at: "2026-10-06T09:35:40Z",
    error: null,
    params: {
      bucket_name: "models",
    },
    output: {
      object_name: "models/job-001/XGBRegressor_optimized_v1.joblib",
    },
  },
};

/**
 * Mẫu 4: Xảy ra lỗi (Failed State)
 */
export const MOCK_PIPELINE_FAILED: PipelineData = {
  job_id: "job-001",
  version: "1.0.0",
  mode: "automl",
  status: "failed",
  updated_at: "2026-10-06T09:31:12Z",
  read_dataset: {
    name: "Read dataset",
    kind: "data_loading",
    depends_on: [],
    status: "done",
    started_at: "2026-10-06T09:28:10Z",
    finished_at: "2026-10-06T09:28:22Z",
    error: null,
    params: {
      id_data: "ds_housing_corrupted",
      format: "parquet",
    },
    output: {
      data_url: "minio://datasets/housing_corrupted.parquet",
      cache_hit: false,
    },
  },
  split_holdout_data: {
    name: "Split holdout data",
    kind: "data_splitting",
    depends_on: ["read_dataset"],
    status: "done",
    started_at: "2026-10-06T09:28:23Z",
    finished_at: "2026-10-06T09:28:30Z",
    error: null,
    params: {
      method: "train_test_split",
      test_size: 0.2,
      shuffle: true,
      random_state: 42,
    },
    output: {
      train_rows: 8000,
      holdout_rows: 2000,
    },
  },
  read_training_data: {
    name: "Read training data",
    kind: "data_loading",
    depends_on: ["split_holdout_data"],
    status: "done",
    started_at: "2026-10-06T09:28:31Z",
    finished_at: "2026-10-06T09:28:38Z",
    error: null,
    params: {
      split: "train",
    },
    output: {
      n_rows: 8000,
      n_columns: 14,
    },
  },
  preprocessing: {
    name: "Preprocessing",
    kind: "preprocessing",
    depends_on: ["read_training_data"],
    status: "failed",
    started_at: "2026-10-06T09:28:39Z",
    finished_at: "2026-10-06T09:29:05Z",
    error: "ValueError: Cột 'target' chứa giá trị không hợp lệ (NaN/Infinity) không thể biến đổi.",
    params: {
      list_feature: ["crim", "zn", "indus"],
      target: "medv",
      transformers: {
        numeric: ["SimpleImputer", "StandardScaler"],
      },
    },
    output: {
      cache_hit: false,
      dropped_rows: null,
      column_types: null,
    },
  },
  model_selection: {
    name: "Model selection",
    kind: "model_selection",
    depends_on: ["preprocessing"],
    status: "pending",
    started_at: null,
    finished_at: null,
    error: null,
    params: {
      problem_type: "regression",
      model_names: ["LinearRegression", "XGBRegressor"],
      metric_sort: "r2",
    },
    output: {},
  },
  train: {
    name: "Train models",
    kind: "model_training",
    depends_on: ["model_selection"],
    status: "pending",
    started_at: null,
    finished_at: null,
    error: null,
    params: {},
    output: { models: {} },
  },
  select_best: {
    name: "Select best model",
    kind: "model_selection",
    depends_on: ["train"],
    status: "pending",
    started_at: null,
    finished_at: null,
    error: null,
    params: { dependency_policy: "all_terminal" },
    output: { best_model: null, time_limit_reached: null },
  },
  save_result: {
    name: "Save result",
    kind: "result_storage",
    depends_on: ["select_best"],
    status: "pending",
    started_at: null,
    finished_at: null,
    error: null,
    params: { bucket_name: "models" },
    output: { object_name: null },
  },
};
