 CLIENT_ID: ""
 CLIENT_SECRET: ""
 SESSION_TIMEOUT: 60
 PORT_BACK_END: 9999
 HOST_BACK_END: "10.100.200.119"
 HOST_FRONT_END: "10.100.200.119"
 PORT_FRONT_END: "3000"
 KAFKA_SERVER: "10.100.200.119:9092"
 MONGODB_CONNECT: "mongodb://10.100.200.119:27017/"