 CLIENT_ID: ""
 CLIENT_SECRET: ""
 SESSION_TIMEOUT: 60
 PORT_BACK_END: 9999
 HOST_BACK_END: "0.0.0.0"
 HOST_FRONT_END: "localhost"
 PORT_FRONT_END: "3000"
 KAFKA_SERVER: "localhost:9092"
 KAFKA_TOPIC: "abc"
 MONGODB_CONNECT: "mongodb://localhost:27017/"