version: '3.8'
services:
  worker-1:
    image: workers:latest
    build:
      context: .
      dockerfile: worker.dockerfile
    command: uvicorn worker:app --host 0.0.0.0 --port 4000
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    environment:
      - HOST=0.0.0.0
      - PORT=4000
      - WORKER_INDEX=1
