version: '3.8'
services:
  worker-1:
    image: workers:latest
    build:
      context: .
      dockerfile: worker.dockerfile
    command: uvicorn worker:app --host 0.0.0.0 --port 4000 --reload
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    environment:
      - HOST=0.0.0.0
      - PORT=4000
      - WORKER_INDEX=1
  worker-2:
    image: workers:latest
    build:
      context: .
      dockerfile: worker.dockerfile
    command: uvicorn worker:app --host 0.0.0.0 --port 4001 --reload
    ports:
      - "4001:4001"
    volumes:
      - .:/app
    environment:
      - HOST=0.0.0.0
      - PORT=4001
      - WORKER_INDEX=2
  worker-3:
    image: workers:latest
    build:
      context: .
      dockerfile: worker.dockerfile
    command: uvicorn worker:app --host 0.0.0.0 --port 4002 --reload
    ports:
      - "4002:4002"
    volumes:
      - .:/app
    environment:
      - HOST=0.0.0.0
      - PORT=4002
      - WORKER_INDEX=3
  worker-4:
    image: workers:latest
    build:
      context: .
      dockerfile: worker.dockerfile
    command: uvicorn worker:app --host 0.0.0.0 --port 4003 --reload
    ports:
      - "4003:4003"
    volumes:
      - .:/app
    environment:
      - HOST=0.0.0.0
      - PORT=4003
      - WORKER_INDEX=4
  worker-5:
    image: workers:latest
    build:
      context: .
      dockerfile: worker.dockerfile
    command: uvicorn worker:app --host 0.0.0.0 --port 4004 --reload
    ports:
      - "4004:4004"
    volumes:
      - .:/app
    environment:
      - HOST=0.0.0.0
      - PORT=4004
      - WORKER_INDEX=5
