choose: "new_model"
metric_sort: accuracy
list_feature:
  - "Administrative_Duration"
  - "ProductRelated"
  - "ProductRelated_Duration"
  - "BounceRates"
  - "ExitRates"
  - "PageValues"
  - "SpecialDay"
  - "Browser"
  - "TrafficType"
  - "VisitorType"
  - "Weekend"

target: "Revenue"

