name: Deploy Documentation to GitHub Pages

# Chạy quy trình này mỗi khi có push lên nhánh main
on:
  push:
    branches:
      - main

# Cho phép quy trình này tạo một GitHub Pages deployment
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install mkdocs-material

      - name: Deploy to GitHub Pages
        # Lệnh này sẽ tự động build trang docs và đẩy nó lên nhánh gh-pages
        run: mkdocs gh-deploy --force
