services:
  worker1:
    build: 
      context: ./worker1
    ports:
      - "4001:4001"
    restart: unless-stopped
    networks:
      - mr-network

  worker2:
    build: 
      context: ./worker2
    ports:
      - "4002:4002"
    restart: unless-stopped
    networks:
      - mr-network

networks:
  mr-network:
    driver: bridge